<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>UT3_EJ1</groupId>
    <artifactId>UT3_EJ1</artifactId>
    <version>1.0.0</version>
    <packaging>jar</packaging>

    <name>UT3_EJ1</name>
    <url>http://hibernate.ut3.ej1.com</url>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <!-- Java version -->
        <maven.compiler.release>21</maven.compiler.release>

        <!-- Versiones centralizadas -->
        <mariadb.driver.version>3.3.3</mariadb.driver.version>
        <hibernate.version>6.4.4.Final</hibernate.version>
        <jakarta.persistence.version>3.1.0</jakarta.persistence.version>
    </properties>

    <dependencies>

        <!-- JDBC MariaDB -->
        <dependency>
            <groupId>org.mariadb.jdbc</groupId>
            <artifactId>mariadb-java-client</artifactId>
            <version>${mariadb.driver.version}</version>
        </dependency>

        <!-- Hibernate Core -->
        <dependency>
            <groupId>org.hibernate.orm</groupId>
            <artifactId>hibernate-core</artifactId>
            <version>${hibernate.version}</version>
        </dependency>

        <!-- Hibernate Dialects -->
        <dependency>
            <groupId>org.hibernate.orm</groupId>
            <artifactId>hibernate-community-dialects</artifactId>
            <version>${hibernate.version}</version>
        </dependency>

        <!-- JPA API -->
        <dependency>
            <groupId>jakarta.persistence</groupId>
            <artifactId>jakarta.persistence-api</artifactId>
            <version>${jakarta.persistence.version}</version>
        </dependency>

       

    </dependencies>

    <profiles>

        <!-- Perfil para DESARROLLO -->
        <profile>
            <id>dev</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>

            <properties>
                <db.url>jdbc:mariadb://localhost:3310/shop_db</db.url>
                <db.user>admin_alvaro</db.user>
                <db.pass>Abcd1234$</db.pass>
                <db.dialect>org.hibernate.dialect.MariaDBDialect</db.dialect>
            </properties>
        </profile>

        <!-- Perfil para TEST o PRE-PRODUCCIÓN -->
      <!--  <profile>
            <id>pre</id>
            <properties>
                <db.url>jdbc:mariadb://192.168.1.100:3310/shop_db</db.url>
                <db.user>pre_user</db.user>
                <db.pass>pre_pass_segura</db.pass>
                <db.dialect>org.hibernate.dialect.MariaDBDialect</db.dialect>
            </properties>
        </profile>-->

        <!-- Perfil para PRODUCCIÓN REAL -->
      <!--  <profile>
            <id>pro</id>
            <properties>
                <db.url>jdbc:mariadb://servidor.produccion.com:3310/shop_db</db.url>
                <db.user>prod_user</db.user>
                <db.pass>!PASS_SUPER_SEGURA!</db.pass>
                <db.dialect>org.hibernate.dialect.MariaDBDialect</db.dialect>
            </properties>
        </profile>-->

    </profiles>

    <build>
        <finalName>${project.artifactId}</finalName>

        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

</project>
